//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topaz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_session
    {
        public int session_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> expiry { get; set; }
        public string user_ip { get; set; }
    }
}
